### ISSUE TITLE
Question: Plugins order and scope

### ISSUE THREAD

**Issue by ozum** [hapipal/haute-couture#41]
Hi,

I have two questions related to plugins directory:

1. How to use plugin names with scope (i.e. `@somescope/somepackagename`)?
1. How to sort plugin registration order? (First this than this)

Please note: I'm aware that I can manually do it via `plugins.js` or `plugins/index.js`. I mean, how to do those using directory structure?

If those are not possible currently, may I suggest:
1. Haute Couture directories may work recursively or at least two levels to cover scope.
1. Optionally a number prefix can be added file names (Optional numbers + point could be ignored in plugin name resolution): (i.e. `01.this-plugin.js`, `02.that-plugin.js`.

Kind regards,

**Comment by ozum** [comment]
By the way, here I share, what I do in `plugins/index.js` in case anyone needs scoped modules:

```js
const klaw = require("klaw-sync");
const { join, extname, relative } = require("path");

/* eslint-disable global-require, import/no-dynamic-require */

const isPlugin = item =>
  typeof item === "object" &&
  ((typeof item.name === "string" && typeof item.register === "function") || (item.plugins && item.plugins.plugin));
const onlyJs = item => !item.stats.isDirectory() && extname(item.path) === ".js" && item.path !== __filename;

module.exports = klaw(join(__dirname), { depthLimit: 1 })
  .filter(onlyJs)
  .map(item => relative(__dirname, item.path))
  .map(item => {
    const obj = require(`./${item}`);
    return isPlugin(obj) ? obj : { ...obj, plugins: { ...obj.plugins, plugin: require(item.replace(extname(item), "")) } };
  });
```

**Comment by ozum** [comment]
> 1. Haute Couture directories may work recursively or at least two levels to cover scope.
> 2. Optionally a number prefix can be added file names (Optional numbers + point could be ignored in plugin name resolution): (i.e. 01.this-plugin.js, 02.that-plugin.js.

@devinivy, for above requirements, I just created [hapi-plugins-dir](https://www.npmjs.com/package/hapi-plugins-dir) module which has 100% test coverage. It's output is 100% compatible with `haute-couture`, and currently I'm using it in `plugins/index.js`. In case you find it useful, you may consider to integrate it in `haute couture`.

**plugins/index.js**
```js
module.exports = require("hapi-plugins-dir")();
```

**Comment by devinivy** [comment]
Hey, thanks for all this thought and the module above.  Just wanted to let you know that I've checked out your approach/questions/requests and am mulling it over.  Design-wise I am trying to keep haute-couture as simple in behavior as possible.  Currently the only room for "magic" in haute-couture is conversion of filenames into to configuration for certain items, and I consider it an API that this currently excludes `plugins/` with a scoped name.

I am less likely to support plugin registration order, partly because I think allowing plugin registration order to matter should be avoided, and renaming files to rename plugin registration order seems like it might not scale very well.  [This article](https://hapipal.com/best-practices/handling-plugin-dependencies) has some more words on the topic.

As you've already leveraged (awesome!!), haute-couture is designed in such a way that you can override all these behaviors on your own by placing an index.js file in the directory, and I would love to see complex behaviors like registration ordering go into separate modules—rather than haute-couture—as you've already done :)

**Comment by ozum** [comment]
Thanks. It's fair to escalate complex behaviors to external modules.

What do you think about scoped modules? In my opinion scoped modules should be included in haute couture anyway, because they are not in complex behavior category, they are just modules.

**Comment by devinivy** [comment]
I agree, we should find a way to support them!  My preference would be to find a way to use filenames rather than deep folders—do you have any ideas in that direction?  If we don't need to support `.` characters in scopes then `plugins/scope-name.package-name.js` might work, for example.

**Comment by ozum** [comment]
You touched a good point. Having an escape hatch is a must. I use same principle for my test helpers, but I forgot to put an escape hatch to [hapi-plugins-dir](https://www.npmjs.com/package/hapi-plugins-dir). What I will do for `hapi-plugins-dir` is, adding an option (`exclude`) with a default value.

```js
// Default folder to exclude could be: exclude, manual, custom
module.exports = require("hapi-plugins-dir")({ exclude: 'my-special-dir' });
```

In that case a developer has following options:
1. `recursive` option decides whether to include all files recursively. (Currently available and default is `true`)
2. `exclude` option will decide what directory to use as an escape hatch if recursion is active. (Not available yet and default could be `exclude`, `manual`, `custom`)

* What do you think about making recursion optional and having a special directory to exclude?
* (For `hapi-plugins-dir`) What could be best default folder name to exclude?

**Comment by ozum** [comment]
I came across decorations in doc and they use `.` as separator.

> * decorations/[type].decoration-name.js - export an object. The type ...

Using `.` as separator in scoped modules (`plugins/@scope.module`) would be a good choice to maintain consistency across the library.

**Comment by devinivy** [comment]
> What do you think about making recursion optional and having a special directory to exclude?

I'm hearing more and more that recursion is desirable, and I'm becoming more interested in it.  I see value particularly for organizing route directories.  We'll have to decide on how it interacts with [`useFilename()`](https://github.com/hapipal/haute-couture/blob/master/lib/manifest.js#L204-L221), and how to configure the behavior of each folder.  I have a couple ideas.  Note that this will require changes to the underlying library [haute](https://github.com/devinivy/haute).

> (For hapi-plugins-dir) What could be best default folder name to exclude?

I always use `helpers/`.  I use it as opposed to `util/` or `utils/` in order to avoid confusion with node's `util` module.

> Using . as separator in scoped modules (plugins/@scope.module) would be a good choice to maintain consistency across the library.

I agree!  That sounds great.  I'm comfortable with the limitation that the scope may not contain a `.` character, given that it's an edge case that's hard to deal with, and there's a simple fallback for this anyway.

**Comment by devinivy** [comment]
For those interested in progress here, check out PR #47.  @ozum I would especially appreciate your feedback, given all the thought you've put into this.

**Comment by ozum** [comment]
@devinivy Great news that recursion is added and could be default in next major version. Thanks for the effort.
