### ISSUE TITLE
Improved decorations handling

### ISSUE THREAD

**Issue by damusix** [hapipal/haute-couture#72]
Writing out a shopping cart app and made a bunch of decorators. I know you are in a refactoring phase for some things now, so I have 2 minor observations that are mostly nice-to-haves:

1) It would be kind of cool if HC allowed us to organize nested decorations, eg:
```
marketplace/decorations
├── request
|   ├── addToCart.js
|   ├── getCart.js
|   ├── handleLogin.js
|   ├── handleLogout.js
|   ├── isAuthenticated.js
|   └── removeFromCart.js
├── server
|   └── marketplace.js
└── toolkit
    └── view.js
```

2) Also, it would be nice to be able to have both the nested structure along side a single file `[name].js` that returns an array of `[{ method, type }]`, so that the same method can be assigned to multiple types, eg:
```
marketplace/decorations
├── request
|   └── blahblah.js
├── toolkit
|   └── view.js
└── marketplace.js
```

`marketplace.js`

```js
module.exports = (server) => {

    const method = () => { /** do stuff */}

    return [
        { method, type: 'server' },
        { method, type: 'request' },
        { method, type: 'toolkit' },
    ]
}
```

Let me know if that makes sense

**Comment by devinivy** [comment]
> It would be kind of cool if HC allowed us to organize nested decorations

Good call, this is happening 👍 I'll be beefing-up support for inferred `type` and `property` of decorations and `type` of extensions.

> Also, it would be nice to be able to have both the nested structure along side a single file [name].js that returns an array of [{ method, type }], so that the same method can be assigned to multiple types

I see what you mean.  Hmm, I think right now it would be hard to support this because everything is designed to be extremely one-to-one with hapi's API, and hapi doesn't allow you to pass an array to `server.decorate()`.  For example, this actually _does_ work with extensions because `server.ext()` accepts an array.  Here's what I'll do: I will setup the filename-to-type mapper for `decorations` to be smart enough to handle arrays, and if you want to support passing arrays you can do so with a custom amendment.  If this all goes well, you'll be able to find this amendment in the tests and I'll reference it here.  If you'd like you can also open an issue in hapi to see if there's interest in making `server.decorate()` and `server.ext()` behave similarly to each other.

**Comment by devinivy** [comment]
Alrighty, here's what I came up with to support the array usage in your application through an amendment in the upcoming version of haute-couture: https://github.com/hapipal/haute-couture/blob/191b84c905ecf9f57530ff2d85e41ef2d8cb8bff/test/closet/decorations-array-amendment/.hc.js#L5-L23

**Comment by damusix** [comment]
I'll pull v4 and test it out and get back. Thank you very much @devinivy!
