### ISSUE TITLE
improve the paths passed to exclude

### ISSUE THREAD

**Issue by paulovieira** [hapipal/haute-couture#78]
Previous note: this issue is observed with v3, but also applies to v4 (because the root cause is in the `haute` module).

Supposed I have these 2 files
```
my-app/lib/services/math.js
my-app/lib/routes/math.js
```
and for some reason I want to exclude the routes defined in `my-app/lib/routes/math.js`. I can use the `exclude` option as a function, like this:
```js
// my-app/lib/.hc.js

module.exports = {
    exclude: function (filename, path) {

        console.log({ filename, path })
        // exclude logic goes here (return true to exclude)
    }
};
```
The problem is that the arguments `filename` and `path` are not as detailed as I expected. In the console I see:
```sh
{ filename: 'math', path: 'math.js' }
{ filename: 'math', path: 'math.js' }
```
so it's impossible to distinguish between them (`path` is always relativized). The problem seems to be in `haute`, precisely in the `relativize` inner function (L39). It would be cool if it added a 3rd argument as the original untouched path. I can make a PR if this is of interest.

NOTE: An alternative would be the `remove` array, but that also doesn't help because it will only mathc "places" (that is, the names of directories under `my-app/lib`; so it could be `remove: ['routes']` but not `remove: ['routes/math.js']`.

**Comment by devinivy** [comment]
Ah, I see what you mean.  If we add a third argument, should it be relative to `dirname` (i.e. `.hc.js`) or should it be absolute?

In the past when I've had this need, I place the `exclude` option directly on the amendment.  Would this work for you?
```js
// .hc.js
'use strict';

const HauteCouture = require('@hapipal/haute-couture');

module.exports = {
  routes: HauteCouture.amendment('routes', {
    exclude: (filename, path) => // ...
  })
};
```

In v3 it is a little bit less pretty to modify an amendment, but the same principle applies:

```js
// .hc.js
'use strict';

const HauteCouture = require('haute-couture');

const defaultManifest = HauteCouture.manifest.create({}, true);
const getItemByPlace = (place) => {

    return defaultManifest.find((amendment) => place === amendment.place);
};

module.exports = {
  add: [
    {
      ...getItemByPlace('routes'),
      exclude: (filename, path) => // ...
    }
  ]
};
```

There is also the possibility to leverage the default behavior and place `math.js` under `routes/helpers/`, which is automatically excluded.

**Comment by paulovieira** [comment]
> Ah, I see what you mean. If we add a third argument, should it be relative to `dirname` (i.e. `.hc.js`) or should it be absolute?

I guess it would be more clean if it was relative to the directory where `.hc.js` is (to avoid leaking details about operating system in logs, for instance),

> 
> In the past when I've had this need, I place the `exclude` option directly on the amendment. Would this work for you? [...]

Thanks, I hadn't tried that to be honest. The API for this module is not so easy for a newcomer, in my opinion (though seems to be simpler with v4). For this particular case (excluding one or a few random files) the most direct solution for me is to use some kind of "filter function", and so `exclude` is the natural solution.

Great work anyway! Looking forward to try the updated version in the @hapipal namespace!

**Comment by Nargonath** [comment]
From what I understand @paulovieira you'd prefer we augment the `exclude` property to receive `relativePath` instead of using the solution @devinivy proposed? If that's so, would you be open to such a feature landing @devinivy?

My 2 cents is that the amendment solution is pretty straightforward when you look at the code so it seems to me that it is easy to grasp once you're aware of its existence. It answers your need and has the advantage of not requiring any further development. On the other hand, the `relativePath` seems to me like an important data for the `exclude` feature to be whole. By the way, is the `path` parameter in the amendment the relative path or is it the same value as @paulovieira raised in his issue?

**Comment by devinivy** [comment]
The way I see it, the reason `exclude` is falling down here is because it's being used as a default configuration for all amendments.  It's a totally reasonable use-case, you just happen to be the first person who has run into it.  When `exclude` is placed on a specific amendment it all makes more sense because the relative `path` is relative to the amendment's `place`, which is typically a directory such as `routes` or `auth/strategies`.  You'll see input such as:

```js
// When applied to a route file, e.g. routes/users/update.js
exclude: (filename, path) => {
  // filename: update
  // path: users/update.js
}
```

It's important background that these are identical arguments as those passed to `useFilename()`, and I think it makes sense to keep `useFilename()` and `exclude()` in step with each other.  In the case of `useFilename()`, we typically aren't interested in including the place (e.g. `routes/`) as part of the file path info.  For example, we use `useFilename()` to set a default route id based on the route's file: we might want to id the route `'users-update'` from its file `routes/users/update.js`, and it would be a little odd to include `route-` in the route's id.  There are several other similar examples in haute-couture.

I see four options we might head:
 - Make no changes.  The downside to this is that it's difficult to use a default `exclude()` config to handle a specific case, which would be convenient, as you don't have to interact with specific amendments.
 - Pass a third argument to `useFilename()`, `exclude()`, and `include()` which contains the place in the path, e.g. `(filename, path, pathWithPlace) => ...`.  The downside of this is that there is lots of duplicate information across the three arguments, e.g. `'update'`, `'users/update.js'`, `routes/users/update.js`.
 - Change the `path` argument to include the place.  One downside is that this is a breaking change.  Another downside is that it would either create a subtle difference between `useFilename()` and `exclude()` arguments (if only `exclude()`'s changes) or be less useful to `useFilename()` (if they both change), since `useFilename()` will usually have to relativize the path by `place`.
 - I think this is my favorite: pass the resolved manifest item itself as the final argument.  This would give `exclude()` the information it needs when it's used as a default configuration to make a very specific exception.  Here's how @paulovieira might solve the original problem with that API (in v3):

```js
// my-app/lib/.hc.js

module.exports = {
    exclude: function (filename, path, { place }) {
        if (place === 'routes' && path === 'math.js') {
            return true;
        }
        return false; // Or your favorite default behavior
    }
};
```

How would we feel about that?  @paulovieira do you plan to move to v4 soon, or if we make a change like this would it only be useful to use if it lands in v3?

**Comment by Nargonath** [comment]
Thanks for the detailed explanation @devinivy. I do like the last solution better too since it provides the most information that people might also want to act upon in the future. 👍

**Comment by paulovieira** [comment]
> The way I see it, the reason `exclude` is falling down here is because it's being used as a default configuration for all amendments. It's a totally reasonable use-case, you just happen to be the first person who has run into it. When `exclude` is placed on a specific amendment it all makes more sense because the relative `path` is relative to the amendment's `place`, which is typically a directory such as `routes` or `auth/strategies`. 

Fully agree! This was indeed the case. I was not aware that amendments could be given for a specific `place`.

The example you give above (for v4) is very clear (not so much for v3...). I will migrate all my code when the general update to hapi-pal is released. I think this issue can be closed.

Thank you very much for the detailed response! Fantastic support!

**Comment by devinivy** [comment]
Quite welcome!  Sounds like a plan.  We can always revisit it in the future too. 👍
